let libro =[
{
titulo:"orgullo y prejuicio",
autor:"Jane Austen",
genero:"romance clasico",
idioma:"español", 
precio:"$10.990",
formato:"tapa blanda",
isbn:"978-19864314480", 
descripcion:"este libro narra la historia de elizabeth bennet y su complicada relacion con el señor darcy en inglaterra delsiglo xx", 
estado:"ficcion clasica", 
ubicacion:"ficion", 
fecha_publicacion:"28 de enero de 1813", 
editorial:"createSpace", 
paginas:"236",
dimension:"11.43*3.18*18.42cm", 
peso:"9.6 onzas", 
 
},
{
titulo:"el amante japones ",
autor:"Isabell Allende",
genero:"romance contemporaneo",
idioma:"español", 
precio:"15.000",
formato:"version kinde",
isbn:"978-19864314480", 
descripcion:"una conmovedora historia de amor que se desarrolla en san francisco.entrelazado en la vida de una joven chef y un joven msterioso hombre japones", 
estado:"antiguo", 
ubicacion:"ficcion contemporanea", 
fecha_publicacion:"25 de mayo del 2015", 
editorial:"plaza & janes editores", 
paginas:"320",
dimension:"11.43*3.18*18.42cm", 
peso:"128 onzas", 
     
 },
{
titulo:"cumbres borrascosas",
autor:"Emyli Bronce",
genero:"romance clasico",
idioma:"español", 
precio:"12.500",
formato:"tapa dura",
isbn:"978-19864314480", 
descripcion:"una apasionante historia de amor yvenganza entre heatchif y catherine en la salvaje y desolada campiña inglesa", 
estado:"antiguo", 
ubicacion:"ficion clasica", 
fecha_publicacion:"13 de diciembre del 1847", 
editorial:"penguin clasicos", 
paginas:"416",
dimension:"11.43*3.18*18.42cm", 
peso:"1 libra", 
     
},
{
titulo:"la sombra del viento",
autor:"Carlos Ruiz Safon",
genero:"romance historico/misterioso",
idioma:"español", 
precio:"18.900",
formato:"tapa blanda",
isbn:"978-19864314480", 
descripcion:"ambientada en la barcelona de la posguerra , este libro cuenta la historia de un joven que se adentra en un misterio que emvulve su libro y autor", 
estado:"antiguo", 
ubicacion:"ficcion contemporanea", 
fecha_publicacion:"17 de marzo del 2001", 
editorial:"planeta publishing",
paginas:"576", 
dimension:"11.43*3.18*18.42cm", 
peso:"1.2 libras", 
         
},
{
titulo:"el tiempo entre costuras",
autor:"maria dueñas",
genero:"romance historico",
idioma:"español", 
precio:"14.400",
formato:"tapa blanda",
isbn:"978-19864314480", 
descripcion:"sira una modista española se ve emvuelta en una trama de amor,espinoje y traicion durante la guerra civil y la seguda guerra  mundial", 
estado:"nuevo", 
ubicacion:"ficion historica", 
fecha_publicacion:"28 de julio del 2011", 
editorial:"atria books", 
paginas:"624",
dimension:"11.43*3.18*18.42cm", 
peso:"1.1 libras", 
             
},
{
titulo:"bajo el sol de media noche",
autor:"sarah lark",
genero:"romance historico",
idioma:"esañol", 
precio:"16.900",
formato:"version kindle",
isbn:"978-19864314480", 
descripcion:"ambientada en nueva zelanda este libro narra la historia de dos mujeres y sus luchas por el amor y la libertad en un entorno exotico y desafiante", 
estado:"nuevo", 
ubicacion:"ficcion contemporanea", 
fecha_publicacion:"12 de marzo del 2013", 
editorial:"grijalbo", 
paginas:"752",
dimension:"11.43*3.18*18.42cm", 
peso:"1.3 libras", 
},
{
titulo:"os pilares de la terra",
autor:"ken follet",
genero:"romance historico",
idioma:"español", 
precio:"22.000",
formato:"tapa blanda",
isbn:"978-19864314480", 
descripcion:"este libro esta enttrelazado las vidas de varias peronajes en torno a la construcion de una catdral gotica", 
estado:"antiguo", 
ubicacion:"ficcion historica", 
fecha_publicacion:"2 de mayo de 1999", 
editorial:"vintage español",
paginas:"1104", 
dimension:"11.43*3.18*18.42cm", 
peso:"2 libras", 
     
},
{
titulo:"el principito",
autor:"antoine de saint",
genero:"literatura infantil",
idioma:"frances", 
precio:"8.900",
formato:"tapia dura",
isbn:"978-19864314480", 
descripcion:"un cuento magico que sigue las aventuras de un pequeño principe", 
estado:"nuevo", 
ubicacion:"ficion infantil", 
fecha_publicacion:"1943", 
editorial:"boka for you young",
paginas:"96", 
dimension:"11.43*3.18*18.42cm", 
peso:"200g", 
     
},
{
titulo:"elamor en los tiempos del colera",
autor:"gabriel garcia marquez",
genero:"novela",
idioma:"español", 
precio:"15.000",
formato:"digital",
isbn:"978-19864314480", 
descripcion:"una historia de amor en un contexto de emfermedad", 
estado:"antiguo", 
ubicacion:"biblioteca de colombia", 
fecha_publicacion:"1985", 
editorial:"sudamerica",
paginas:"368", 
dimension:"11.43*3.18*18.42cm", 
peso:"500g", 
     
},
{
titulo:"cien años de soledad",
autor:"gabriel garcia marquez",
genero:"novela",
idioma:"español", 
precio:"20.000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"un clasico de la literatura latinoamericana", 
estado:"antiguo", 
ubicacion:"libreria lerner", 
fecha_publicacion:"1967 ", 
editorial:"sudafrica",
paginas:"432", 
dimension:"11.43*3.18*18.42cm", 
peso:"600g", 
     
},
{
titulo:"harry potter la filosofia de la piedra",
autor:"j.k rowlmg",
genero:"fantasia",
idioma:"español", 
precio:"25.000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"la primera entrega de la famosa saga de harry potter",  
estado:"antiguo", 
ubicacion:"libreria nacional", 
fecha_publicacion:"1997", 
editorial:"salamandra",
paginas:"256", 
dimension:"11.43*3.18*18.42cm", 
peso:"700g", 
     
},
{
titulo:"1984",
autor:"geoge orwell",
genero:"ciencia ficion",
idioma:"español", 
precio:"18000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"una diptosia clasica qque ha resistido la prueba del tiempo", 
estado:"antiguo", 
ubicacion:"libreria nacional", 
fecha_publicacion:"1949", 
editorial:"DeBolsillo",
paginas:"368", 
dimension:"11.43*3.18*18.42cm", 
peso:"450g", 
     
},
{
titulo:"la sombra del viento",
autor:"carlos ruiz safon",
genero:"misterio",
idioma:"español", 
precio:"22000",
formato:"digital",
isbn:"978-19864314480", 
descripcion:"una novela que conmbina con misterio ,romance y suspenso en la barcelona de pusguerra", 
estado:"antiguo", 
ubicacion:"libreria nacional", 
fecha_publicacion:"2001", 
editorial:"planeta",
paginas:"544", 
dimension:"11.43*3.18*18.42cm", 
peso:"800g", 
     
},
{
titulo:"rayuela",
autor:"julio cortazar",
genero:"ficcion",
idioma:"español", 
precio:"16000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"una novela imnovadora que desafia las convensiones literarias", 
estado:"antiguo", 
ubicacion:"libreria nacional", 
fecha_publicacion:"1963", 
editorial:"alfaguara",
paginas:"656", 
dimension:"11.43*3.18*18.42cm", 
peso:"900g", 
 },
 {
titulo:"cronicas de una muerte anunciada",
autor:"gabriel garcia marquez",
genero:"novela",
idioma:"español", 
precio:"14000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"una historia de honor venganza y tragedia de un pequeño pueblo", 
estado:"antiguo", 
ubicacion:"lberia nacional", 
fecha_publicacion:"1981", 
editorial:"sudaAmerica",
paginas:"128", 
dimension:"11.43*3.18*18.42cm", 
peso:"300g", 
},
{
titulo:"el laberinto de los espiritus",
autor:"carlos ruiz safon",
genero:"misterio",
idioma:"español", 
precio:"24000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"la ultima entrega de la saga del cementerio de los libros olvidados", 
estado:"nuevo", 
ubicacion:"libreria nacional", 
fecha_publicacion:"2016", 
editorial:"planeta",
paginas:"928", 
 dimension:"11.43*3.18*18.42cm", 
peso:"1100g", 
},
{
titulo:"don quijote de la mancha",
autor:"miguel de cervantes",
genero:"novela",
idioma:"español", 
 precio:"19000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"una obra maestra de la literatura española que sigue las aventura de un caballero soñador", 
estado:"antiguo", 
ubicacion:"libreria lerner", 
fecha_publicacion:"1605", 
editorial:"espasa calpe",
paginas:"1056", 
dimension:"11.43*3.18*18.42cm", 
peso:"1200g", 
},
{
titulo:"los juegos del hambre",
autor:"zussane collins",
genero:"ciencia ficcion",
idioma:"español", 
precio:"17000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"una diptosia donde los jovenes luchan por sobrevivir en un reality show mortal", 
estado:"nuevo", 
ubicacion:"libreria nacional", 
fecha_publicacion:"2008", 
editorial:"molino",
paginas:"400", 
dimension:"11.43*3.18*18.42cm", 
peso:"600g", 
},
{
titulo:"el alquimista",
autor:"pablo coelh",
genero:"ficcion",
idioma:"español", 
precio:"13000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"una historia de busqueda personal y espiritualidad que inspirado a millones de lectores", 
estado:"nuevo", 
ubicacion:"libreria lerne", 
fecha_publicacion:"2008", 
editorial:"rayo",
paginas:"208", 
dimension:"11.43*3.18*18.42cm", 
peso:"350g",
},
{
titulo:"la casa de los espiritus",
autor:"isabel allende",
genero:"novela",
idioma:"español", 
precio:"21000",
formato:"fisico",
isbn:"978-19864314480", 
descripcion:"una saga familiar qe combina realismo magico y politica en un pais latinoamericano ficticio", 
estado:"nuevo", 
ubicacion:"libreria nacional", 
fecha_publicacion:"1982", 
editorial:"plaza  & janes",
paginas:"576", 
dimension:"11.43*3.18*18.42cm", 
peso:"700g", 
},
]
  
